web/router.ex
defmodule ArayashikiWs.Router do
  use ArayashikiWs.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug ArayashikiWs.Headers
  end

  pipeline :api_auth do
    plug Guardian.Plug.VerifyHeader 
    plug Guardian.Plug.LoadResource
  end

  scope "/", ArayashikiWs do
    pipe_through [:browser, :browser_auth]

    get "/", PageController, :index
    get "/login",  SessionController, :new
    post "/login",  SessionController, :create
    get "/logout", SessionController, :delete
    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/tip_cards", TipCardController
  end

  scope "/api", ArayashikiWs do
    pipe_through [:api, :api_auth]

    get "/menstrual_cycle/:wish_date", CalculatorController, :menstrual_cycle

    post "/response_cards", CardController, :response_cards
    get "/tip_cards", CardController, :tip_cards

    get "/interactive_cards", InteractiveCardController, :interactive_cards
    post "/hide_interactive_card", InteractiveCardController, :hide_interactive_card

    post "/onboarding_questions", MobileUserController, :onboarding_questions
    post "/create_login_by_email", MobileUserController, :create_by_email
    post "/login_by_email", MobileUserController, :login_by_email
    post "/login_by_google", MobileUserController, :login_by_google
  end
end

web/views/layout_view.ex
defmodule ArayashikiWs.LayoutView do
  use ArayashikiWs.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <title>Lunna</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white">

    <div class="page-wrapper">
      <div class="page-header navbar navbar-fixed-top">
        <div class="page-header-inner ">
          <%= render "top-menu.html", assigns %>
        </div>
      </div>

      <div class="clearfix"> </div>

      <div class="page-container">
        <%= render "sidebar.html", assigns %>
        <div class="page-content-wrapper">
          <div class="page-content">
            <%
              info = get_flash(@conn, :info)
              error = get_flash(@conn, :error)
            %>
            <%= if info do %>
              <div class="alert alert-info" role="alert"><%= info %></div>
              <br>
            <% end %>
            <%= if error do %>
              <div class="alert alert-danger" role="alert"><%= error %></div>
              <br>
            <% end %>
            <%= render @view_module, @view_template, assigns %>
          </div>
        </div>
      </div>
      <%= render "footer.html", assigns %>
    </div>
    <!--[if lt IE 9]>
    <script src="/assets/global/plugins/respond.min.js"></script>
    <script src="/assets/global/plugins/excanvas.min.js"></script>
    <![endif]-->
    <!-- BEGIN CORE PLUGINS -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <!-- END THEME LAYOUT SCRIPTS -->
  </body>
</html>

web/templates/layout/footer.html.eex
<div class="page-footer">
  <div class="page-footer-inner"> 
    <%= DateTime.utc_now.year %> © Lunna. <a target="_blank" href="http://www.developerS2.com">DeveloperS2</a>
  </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />    
    <meta name="author" content="">
    <title>Session</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

    <body class=" login">
        <!-- BEGIN LOGO -->
        <div class="logo">
          <a href="index.html">
            <img src="/assets/images/logo.png" alt="" />
          </a>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN LOGIN -->
        <div class="content">
          <!-- BEGIN LOGIN FORM -->
          <%
            info = get_flash(@conn, :info)
            error = get_flash(@conn, :error)
          %>
          <%= if info do %>
            <div class="alert alert-info" role="alert"><%= info %></div>
          <% end %>
          <%= if error do %>
            <div class="alert alert-danger" role="alert"><%= error %></div>
          <% end %>
          <%= render @view_module, @view_template, assigns %>
          <!-- END LOGIN FORM -->
        </div>
        <div class="copyright"> <%= DateTime.utc_now.year %> © Lunna. <a target="_blank" href="http://www.developerS2.com">DeveloperS2</a> </div>
</body>
  
</html>

web/templates/layout/sidebar.html.eex
<div class="page-sidebar-wrapper">
  <div class="page-sidebar navbar-collapse collapse">
      <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
          <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
          <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
          <li class="sidebar-toggler-wrapper hide">
              <div class="sidebar-toggler">
                  <span></span>
              </div>
          </li>
          <!-- END SIDEBAR TOGGLER BUTTON -->
          <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->

          <% 
            controller_name =  List.last(String.split((inspect @conn.private.phoenix_controller), "."))

            # item without submenu
            dashboard_active = if (controller_name == "PageController"), do: "active", else: ""
            dashboard_selected = if (controller_name == "PageController"), do: "<span class='selected'></span>", else: ""

            tip_card_active = if (controller_name == "TipCardController"), do: "active", else: ""
            tip_card_selected = if (controller_name == "TipCardController"), do: "<span class='selected'></span>", else: ""
            
          %>

          <li class="nav-item start <%= dashboard_active %>">
            <%= link html_escape({:safe, "<i class='icon-home'></i> Dashboard #{dashboard_selected}"}), to: page_path(@conn, :index), class: "nav-link nav-toggle" %>            
          </li>
          <li class="nav-item start <%= tip_card_active %>">
            <%= link html_escape({:safe, "<i class='icon-bulb'></i> #{gettext("locale_tip_card")} #{tip_card_selected}"}), to: tip_card_path(@conn, :index), class: "nav-link nav-toggle" %>
          </li>
         <!-- 
          <li class="nav-item">
              <a href="javascript:;" class="nav-link nav-toggle">
                  <i class="icon-puzzle"></i>
                  <span class="title">Example Child</span>
                  <span class="arrow"></span>
              </a>
              <ul class="sub-menu">
                  <li class="nav-item">
                      <a href="components_date_time_pickers.html" class="nav-link ">
                          <span class="title">Child 1</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a href="components_select2.html" class="nav-link ">
                          <span class="title">Child 2</span>
                      </a>
                  </li>
                 </li>
                  <li class="nav-item">
                      <a href="components_noui_sliders.html" class="nav-link ">
                          <span class="title">Child 3</span>
                      </a>
                  </li>
                  <li class="nav-item">
                      <a href="components_knob_dials.html" class="nav-link ">
                          <span class="title">Child 4</span>
                      </a>
                  </li>
              </ul>
              </li>
         -->
      </ul>
      <!-- END SIDEBAR MENU -->
      <!-- END SIDEBAR MENU -->
  </div>
</div>

web/templates/layout/top-menu.html.eex
<div class="page-logo">
    <a href="index.html">
        <img src="/assets/images/logo.png" alt="logo" class="logo-default" /> </a>
</div>
<!-- END LOGO -->
<!-- BEGIN RESPONSIVE MENU TOGGLER -->
<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    <span></span>
</a>
<!-- END RESPONSIVE MENU TOGGLER -->
<!-- BEGIN TOP NAVIGATION MENU -->
<div class="top-menu">
    <ul class="nav navbar-nav pull-right">
        <li class="dropdown dropdown-user">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                <img alt="" class="img-circle" src="/assets/images/admin_user.jpg" />
                <span class="username username-hide-on-mobile"> User </span>
                <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-default">
                <li>
                    <%= link to: registration_path(@conn, :new), method: :get do %> 
                      <i class="icon-user"></i>Create account
                    <% end %> 
                </li>
                <li class="divider"> </li>
                <li>
                    <%= link to: session_path(@conn, :delete), method: :get do %> 
                      <i class="icon-key"></i>Log Out
                    <% end %> 
                </li>
            </ul>
        </li>
    </ul>
</div>